/*
 *  Copyright 2018 The WebRTC project authors. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license
 *  that can be found in the LICENSE file in the root of the source
 *  tree. An additional intellectual property rights grant can be found
 *  in the file PATENTS.  All contributing project authors may
 *  be found in the AUTHORS file in the root of the source tree.
 */

#ifndef CAFFEINE_RTC_CAFFEINE_H
#define CAFFEINE_RTC_CAFFEINE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(CAFFEINE_RTC_LIBRARY)
#if defined(_WIN32)
#define CAFFEINE_API __declspec(dllexport)
#else
#define CAFFEINE_API __attribute__((visibility("default")))
#endif
#elif defined(_WIN32)
#define CAFFEINE_API __declspec(dllimport)
#else
#define CAFFEINE_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Log severities mapped from WebRTC */
typedef enum {
  CAFF_LOG_SENSITIVE,
  CAFF_LOG_VERBOSE,
  CAFF_LOG_INFO,
  CAFF_LOG_WARNING,
  CAFF_LOG_ERROR,
  CAFF_LOG_NONE,
} caff_log_severity;

/* Video formats mapped from WebRTC */
typedef enum {
  CAFF_FORMAT_UNKNOWN,
  CAFF_FORMAT_I420,
  CAFF_FORMAT_IYUV,
  CAFF_FORMAT_RGB24,
  CAFF_FORMAT_ABGR,
  CAFF_FORMAT_ARGB,
  CAFF_FORMAT_ARGB4444,
  CAFF_FORMAT_RGB565,
  CAFF_FORMAT_ARGB1555,
  CAFF_FORMAT_YUY2,
  CAFF_FORMAT_YV12,
  CAFF_FORMAT_UYVY,
  CAFF_FORMAT_MJPEG,
  CAFF_FORMAT_NV21,
  CAFF_FORMAT_NV12,
  CAFF_FORMAT_BGRA,
} caff_format;

/* Errors generated by caffeine layer */
typedef enum {
  CAFF_ERROR_SDP_OFFER,
  CAFF_ERROR_SDP_ANSWER,
  CAFF_ERROR_ICE_TRICKLE,
  CAFF_ERROR_TAKEOVER,
  CAFF_ERROR_DISCONNECTED,
  CAFF_ERROR_BROADCAST_FAILED,
  CAFF_ERROR_UNKNOWN,
} caff_error;

/* Callback type for WebRTC log messages */
typedef void (*caff_log_callback)(caff_log_severity severity,
                                  char const* message);

/* Struct for ICE offers/answers */
typedef struct {
  char const* sdp;
  char const* sdp_mid;
  int sdp_mline_index;
} caff_ice_info;

typedef caff_ice_info const caff_ice_candidates[];

/* Callback types for starting stream */

/* TODO: Move SDP & ICE stuff under the hood
 */
typedef char const* (*caff_offer_generated)(void* user_data, char const* offer);
typedef bool (*caff_ice_gathered)(void* user_data,
                                  caff_ice_candidates candidates,
                                  size_t num_candidates);
typedef void (*caff_stream_started)(void* user_data);
typedef void (*caff_stream_failed)(void* user_data, caff_error error);

/* Opaque handles to internal objects */
struct caff_interface;
typedef struct caff_interface* caff_interface_handle;

struct caff_stream;
typedef struct caff_stream* caff_stream_handle;

/* Get string representation of error enum
 *
 * TODO: localization support
 *
 * error: the error code
 *
 * Returns a string representing the given error or "Unknown" if out of range
 */
CAFFEINE_API
char const* caff_error_string(caff_error error);

/* Initialize the Caffeine library
 *
 * log_callback: a function to call for WebRTC generated log messages
 * min_severity: sets the lowest log severity required for the callback to fire
 *
 * Returns a handle to the caffeine management object to be passed into other
 * functions. If there is an error during initialization this will be NULL
 */
CAFFEINE_API
caff_interface_handle caff_initialize(caff_log_callback log_callback,
                                      caff_log_severity min_severity);

/* Start stream on Caffeine
 *
 * Sets up the WebRTC connection with Caffeine asynchronously. Calls
 * into started_callback or failed_callback with the result. This may
 * happen on a different thread than the caller.
 *
 * **TODO**: move SDP offer/answer and ICE negotiation inside the library (i.e.
 * remove offer_generated_callback and ice_gathered_callback)
 *
 * interface_handle: handle to the caffeine interface from caff_initialize
 * user_data: an optional pointer passed blindly to the callbacks
 * started_callback: called when stream successfully starts
 * failed_callback: called when stream fails to start
 *
 * returns a handle to the stream. If an error occurs before starting
 * the asynchronous operation, the handle will be NULL and the
 * failed_callback will NOT be called
 */
CAFFEINE_API
caff_stream_handle caff_start_stream(
    caff_interface_handle interface_handle,
    void* user_data,
    caff_offer_generated offer_generated_callback,
    caff_ice_gathered ice_gathered_callback,
    caff_stream_started started_callback,
    caff_stream_failed failed_callback);

/* TODO pass format, channels, etc */
CAFFEINE_API
void caff_send_audio(caff_stream_handle stream_handle,
                     uint8_t* samples,
                     size_t samples_per_channel);

/* todo pass pixel format */
CAFFEINE_API
void caff_send_video(caff_stream_handle stream_handle,
                     uint8_t const* frame_data,
                     size_t frame_bytes,
                     int32_t width,
                     int32_t height,
                     caff_format format);

/* End a Caffeine stream
 *
 * This signals the server to end the stream and closes the RTC connection.
 *
 * stream_handle: the stream handle received from caff_start_stream.
 *     This handle will no longer be valid after the function returns.
 */
CAFFEINE_API
void caff_end_stream(caff_stream_handle* stream_handle);

/* Deinitialize Caffeine library
 *
 * This destroys the internal factory objects, shuts down worker threads, etc.
 *
 * interface_handle: the interface handle received from caff_initialize. This
 *     handle will no longer be valid after the function returns.
 */
CAFFEINE_API
void caff_deinitialize(caff_interface_handle* interface_handle);

#ifdef __cplusplus
}
#endif

#endif /* CAFFEINE_RTC_CAFFEINE_H */
